sigma: 15
runsetting:
#  new continue
  command: new
  filepath: 'run/Ima-RGB-C2024.10.07--16-20-00'

dataset:
#ImageDataset_XYZ ImageDataset_sRGB PPR_ImageDataset_sRGB
  name: ImageDataset_XYZ
  #d:/aipro/lkj/data /mnt/d/aipro/lkj/data
  data_root: F:\\hddata
#  target_c target_a target_b expertC
  version: expertC
  batch_size: 1
#  450
  img_size: 450
  n_cpu: 1
train:
  lut:
    ch_radio: 4
    press_radio: 8
  lut_n: 3
  lut_dim: 33
  seed: 15
  channel: 3
  device: cuda:0
  expan_att_chans: 4
  n_epochs: 300
  print_each_step: 5
  embed_dim: 16
  patch_size: 32
  lut_weight: 1
  ir_weight: 1
  lambda_smooth: 0.0001
  lambda_monotonicity: 10.0
  lr: 0.0002
  b1: 0.9
  b2: 0.999
  schedule_iter: 10
