# 1 cnn 2 sa
#noise level in denoising or compression level in jpeg compression artifact reduction
sigma: 15
runsetting:
#  new continue
  command: new
  filepath: 'run/Ima-RGB-C-ch4-cp8 2024.06.14--15-13-43'

dataset:
#ImageDataset_XYZ ImageDataset_sRGB PPR_ImageDataset_sRGB
  name: ImageDataset_sRGB
  #d:/aipro/lkj/data /mnt/d/aipro/lkj/data
  data_root: E:\lh\data
#  target_c target_a target_b expertC
  version: expertC
  batch_size: 1
  n_cpu: 1
train:
  lut:
#    cat double-co  cnn sa
    lead_strady: 'co'
    lut_share: True
    att_share: False
    ch_radio: 4
    press_radio: 8
  lut_n: 3
  lut_dim: 33
  seed: 15
  channel: 3
  device: cuda:0
  isRefine: True
  expan_att_chans: 4
  refine_share: True
  n_epochs: 300
  print_each_step: 5
  embed_dim: 16
  patch_size: 64
  lut_weight: 1
  ir_weight: 1
  lambda_smooth: 0.0001
  lambda_monotonicity: 10.0
  lr: 0.0002
  b1: 0.9
  b2: 0.999
  schedule_iter: 10
